CREATE OR REPLACE MATERIALIZED VIEW MV_AGG_CRIME_BY_POSTCODE (
    CRIME_MONTH
    ,CRIME_TYPE
    ,POSTCODE
    ,CNT
) CLUSTER BY (
    POSTCODE
) AS
SELECT
    CRIME_MONTH
    ,CRIME_LOCATION_TYPE
    ,REPORT_POSTCODE
    ,COUNT(1)
FROM FACT.CRIME
GROUP BY
    1, 2, 3;

CREATE OR REPLACE MATERIALIZED VIEW MV_AGG_CRIME (
    CRIME_MONTH
    ,CRIME_TYPE
    ,CNT
) CLUSTER BY (
    CRIME_MONTH
) AS
SELECT
    CRIME_MONTH
    ,CRIME_LOCATION_TYPE
    ,COUNT(1)
FROM FACT.CRIME
GROUP BY
    1, 2;
