CREATE OR REPLACE PROCEDURE LANDING.LOAD_INCREMENTAL()
RETURNS INTEGER NOT NULL
LANGUAGE SQL
AS
DECLARE
    retCode INT DEFAULT 0;
BEGIN
    
    MERGE INTO FACT.CRIME AS TGT
    USING LANDING.CRIME AS SRC ON
        SRC.REPORT_POSTCODE = TGT.REPORT_POSTCODE
        AND SRC.REPORT_MONTH = TGT.REPORT_MONTH
    WHEN MATCHED THEN
        UPDATE SET
            TGT.CRIME_CATEGORY = SRC.CRIME_CATEGORY
            ,TGT.CRIME_LOCATION_TYPE = SRC.CRIME_LOCATION_TYPE
            ,TGT.CRIME_CONTEXT = SRC.CRIME_CONTEXT
            ,TGT.CRIME_OUTCOME_STATUS = SRC.CRIME_OUTCOME_STATUS
            ,TGT.CRIME_PERSISTENT_ID = SRC.CRIME_PERSISTENT_ID
            ,TGT.API_ID = SRC.API_ID
            ,TGT.CRIME_LOCATION_SUBTYPE = SRC.CRIME_LOCATION_SUBTYPE
            ,TGT.CRIME_MONTH = SRC.CRIME_MONTH
            ,TGT.CRIME_LATITUDE = SRC.CRIME_LATITUDE
            ,TGT.CRIME_STREET_ID = SRC.CRIME_STREET_ID
            ,TGT.CRIME_STREET_NAME = SRC.CRIME_STREET_NAME
            ,TGT.CRIME_LONGITUDE = SRC.CRIME_LONGITUDE
            ,TGT.CRIME_OUTCOME_STATUS_CATEGORY = SRC.CRIME_OUTCOME_STATUS_CATEGORY
            ,TGT.CRIME_OUTCOME_STATUS_MONTH = SRC.CRIME_OUTCOME_STATUS_MONTH
            ,TGT.REPORT_LATITUDE = SRC.REPORT_LATITUDE
            ,TGT.REPORT_LONGITUDE = SRC.REPORT_LONGITUDE
            ,TGT.REPORT_POSTCODE = SRC.REPORT_POSTCODE
            ,TGT.REPORT_MONTH = SRC.REPORT_MONTH
    WHEN NOT MATCHED THEN
        INSERT (
            CRIME_CATEGORY
            ,CRIME_LOCATION_TYPE
            ,CRIME_CONTEXT
            ,CRIME_OUTCOME_STATUS
            ,CRIME_PERSISTENT_ID
            ,API_ID
            ,CRIME_LOCATION_SUBTYPE
            ,CRIME_MONTH
            ,CRIME_LATITUDE
            ,CRIME_STREET_ID
            ,CRIME_STREET_NAME
            ,CRIME_LONGITUDE
            ,CRIME_OUTCOME_STATUS_CATEGORY
            ,CRIME_OUTCOME_STATUS_MONTH
            ,REPORT_LATITUDE
            ,REPORT_LONGITUDE
            ,REPORT_POSTCODE
            ,REPORT_MONTH
        ) VALUES (
            SRC.CRIME_CATEGORY
            ,SRC.CRIME_LOCATION_TYPE
            ,SRC.CRIME_CONTEXT
            ,SRC.CRIME_OUTCOME_STATUS
            ,SRC.CRIME_PERSISTENT_ID
            ,SRC.API_ID
            ,SRC.CRIME_LOCATION_SUBTYPE
            ,SRC.CRIME_MONTH
            ,SRC.CRIME_LATITUDE
            ,SRC.CRIME_STREET_ID
            ,SRC.CRIME_STREET_NAME
            ,SRC.CRIME_LONGITUDE
            ,SRC.CRIME_OUTCOME_STATUS_CATEGORY
            ,SRC.CRIME_OUTCOME_STATUS_MONTH
            ,SRC.REPORT_LATITUDE
            ,SRC.REPORT_LONGITUDE
            ,SRC.REPORT_POSTCODE
            ,SRC.REPORT_MONTH
        );

    RETURN retCode;
END;

CALL LANDING.LOAD_INCREMENTAL();
